### ISSUE TITLE
link de acompanhamento

### ISSUE THREAD

**Issue by lucas-carrijo** [servicosgovbr/manual-avaliacao#3]
Olá, estava tentando acessar o link: https://api-acompanha-avalia-servicos.dev.nuvem.gov.br/api/acompanhamento/swagger-ui.html
sabem me dizer se está disponivel?

**Comment by ciagoss** [comment]
Olá @lucas-carrijo, tudo bem? Acredito que o erro encontrado pode ser alguma indisponibilidade momentânea. Foi criado um canal de comunicação no portal Gov.br https://www.gov.br/pt-br/temas/pagina-de-apoio-a-avaliacao-de-servicos-publicos-digitais que pode ser utilizado para solicitar ajuda, dúvidas frequentes e demais informações referente a integrações com a API de Avaliações.
